import Hero from '../components/Hero';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import Slider from '@/components/Slider';
import { SliderData } from '@/components/SliderData';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>COSMOS Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading="COSMOS" message="The universe seen as a well-ordered whole." />
      <Slider slides={SliderData} />
    </>
  );
}
